FROM node:9-alpine
LABEL version="1.0.0"
LABEL greenlight.version="1.0.0"
LABEL greenlight.name="greenlight/b"
LABEL greenlight.description="plugin b"

COPY index.js /app/

ENTRYPOINT ["/app/index.js"]
