FROM node:9-alpine
LABEL version="1.0.0"
LABEL greenlight.version="1.0.0"
LABEL greenlight.name="greenlight/a"
LABEL greenlight.description="plugin a"

COPY index.js /app/

ENTRYPOINT ["/app/index.js"]
